AWSTemplateFormatVersion: 2010-09-09
Description: Application_Layer Template

Parameters:
  NameBase: 
    Description: for security
    Type: String
    Default: lecture10
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - m1.small
      - m1.large
  DBInstanceIdentifier:
    Type: String
  DBInstanceType:
    Type: String
    Default: db.t2.micro
    AllowedValues:
      - db.t2.micro
      - db.t2.small
      - db.t2.medium
  DBSubnetGroupDescription:
    Type: String
  S3BucketName:
    Type: String
  EC2AMI:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: "/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2"
    Description: The AMI ID for the EC2 instance
  
Resources:
# EC2作成
  EC2:
    Type: AWS::EC2::Instance
    Properties:
      NetworkInterfaces:
        - SubnetId: !ImportValue lecture10-PublicSubnet1id
          GroupSet:
            - !ImportValue lecture10-SecurityGroupEC2
          DeviceIndex: 0
      InstanceType: !Ref InstanceType
      ImageId: !Ref EC2AMI
      IamInstanceProfile: !Ref S3AccessInstanceProfile
      Tags:
        - Key: Name
          Value: !Sub  ${NameBase}-ec21a
      KeyName: kadai4-key
      
      
# IAMロールS3接続
  S3AccessRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "ec2.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/"
  
  AccessPolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: s3access
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
              - s3:GetObject
              - s3:PutObject
              - s3:ListBucket
              - s3:DeleteObject
              - s3:GetBucketLocation
          Resource: "arn:aws:s3:::*"
        - Effect: Allow
          Action: "*"
          Resource:
            - "arn:aws:s3:::<lecture10-clf-bucket>"
            - "arn:aws:s3:::<lecture10-clf-bucket>/*"
      Roles:
      - !Ref S3AccessRole
  
  S3AccessInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
      - !Ref S3AccessRole 
      
Outputs:
  InstanceId:
    Description: The Instance ID
    Value: !Ref EC2
    Export:
      Name: !Sub  ${NameBase}-ec2id

  
